# To install the git pre-commit hook run:
#   pre-commit install
# To run pre-commit hooks manually on all files run:
#   pre-commit run --all-files

repos:
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/python-poetry/poetry.git
    rev: 1.8.4
    hooks:
      - id: poetry-check
      - id: poetry-install
        stages: [post-checkout, post-merge]
        always_run: true
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/python-poetry/poetry-plugin-export.git
    rev: 1.8.0
    hooks:
      - id: poetry-export
        args: [-f, requirements.txt, -o, requirements.txt, --with, dev, --all-extras, --without-hashes]
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10240]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: .txt
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: .pdf|.svg|.graphml
      - id: pretty-format-json
        exclude: .ipynb
        args: [--autofix]
      - id: mixed-line-ending
        exclude: .pdf|.svg|.graphml
      - id: check-merge-conflict
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
  - repo: https://gitlab.intra.infineon.com/public-mirror/github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --explicit-package-bases]
        additional_dependencies: [types-requests, types-python-slugify, types-pytz]
